import './styles/root.css'
import './styles/style.css'
import './styles/utilities.css'
import './styles/webkit.css'
import './styles/navbar.css'
import './styles/animations.css'
import './styles/card.css'

import './scripts/data'
import './scripts/carousel'
import './scripts/navbar'
import './scripts/cards'
